---
title: "Lösung Aufgabe plot17"
output: 
  html_document: 
    fig_caption: yes
    highlight: pygments
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_float: yes
bibliography: literatur.bib    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(kableExtra, warn.conflicts = FALSE, quietly=TRUE)
library(tidyverse, warn.conflicts = FALSE, quietly=TRUE)
library(DT, warn.conflicts = FALSE, quietly=TRUE)

library(RColorBrewer)
myPalette <- brewer.pal(8, "RdBu")

options(digits=3)
```

# Ein Beispiel aus McClave Benson
Wir verwenden Daten aus [@mcclave_91] als Einstiegsbeispiel für einen gepaarten t-Test.

```{r daten, message=FALSE, echo=TRUE}
daten <- read_csv2(file="data/restaurants.csv",
                   show_col_types = FALSE)

daten$Restaurant <- as_factor(daten$Restaurant)
datatable(daten)
```


# Box-Plot

Wir erstellen ein Box-Plot, denn wir müssen dieses Ergebnis
diskutieren.

```{r restobox,  message=FALSE, echo=TRUE, warnings=FALSE}
ggplot(daten)  +
  geom_boxplot(mapping=aes(x=Restaurant, 
                           y = Umsatz), 
                           fill=myPalette[3]) +
  labs(
    title="Umsätze in zwei Restaurants", 
    x="", 
    y="Umsatz in Euro"
  ) +
  theme(legend.position = "none")


ggsave(filename="restaurantBox.png", 
       plot=last_plot(), 
       device="png",
       path="./images/", 
       width=16, height=9, units="cm")
```

# Dot-Plot mit ggplot
Wir haben Daten aus 12 Tagen, die wir jetzt als Strings generieren und dem Tibble hinzufügen.

```{r tage, message=FALSE, echo=TRUE}
days <- c("Montag1",
          "Dienstag1",
          "Mittwoch1",
          "Donnerstag1",
          "Freitag1",
          "Samstag1",
          "Montag2",
          "Dienstag2",
          "Mittwoch2",
          "Donnerstag2",
          "Freitag2",
          "Samstag2")

days_double <- c(days, days)

daten <- tibble(Tage=as_factor(days_double), 
                Umsatz=daten$Umsatz, 
                Restaurant=daten$Restaurant)


datatable(daten)
```

```{r dotplot, message=FALSE, echo=TRUE}
ggplot(daten, aes(x=Umsatz, y=Tage, color=Restaurant)) + 
  geom_point() +
  scale_color_brewer(palette="Set2") +
  scale_y_discrete(limits=c("Samstag2", 
                            "Freitag2",
                            "Donnerstag2",
                            "Mittwoch2",
                            "Dienstag2",
                            "Montag2",
                            "Samstag1",
                            "Freitag1",
                            "Donnerstag1",
                            "Mittwoch1",
                            "Dienstag1",
                            "Montag1")
                   ) +
   labs(
    title="Umsätze in zwei Restaurants", 
    x="Umsatz in Euro", 
    y="Wochentage"
  ) 

ggsave(filename="restaurantDotPlot.png", 
       plot=last_plot(), 
       device="png",
       path="./images/", 
       width=16, height=9, units="cm")
```

# Literaturverzeichnis



