---
title: "Dashboard mit HTMLwidgets"
author: "Manfred Brill"
output: 
    flexdashboard::flex_dashboard
encoding: utf-8
---

```{r setup, include = FALSE}
library(tidyverse)
suppressPackageStartupMessages(library(tidyverse))
library(plotly)
suppressPackageStartupMessages(library(plotly))
library(dygraphs)
suppressPackageStartupMessages(library(dygraphs))
library(DT)
suppressPackageStartupMessages(library(DT))
library(leaflet)
suppressPackageStartupMessages(library(leaflet))
library(visNetwork)
suppressPackageStartupMessages(library(visNetwork))

knitr::opts_chunk$set(fig.width = 5, fig.asp = 1/3)
```

# Histogramm

```{r schliff, message=TRUE, warning=TRUE}
schliff <- ggplot(diamonds, aes(cut)) + 
  geom_bar( fill="orange", color="black") +
  labs(
    x = "Schliff",
    y = ""
  )
ggplotly(schliff)
```

# Zeitreihen mit Dygraphs

```{r timeseries, results='markup'}
library(dygraphs)
dygraph(nhtemp, main = "Temperaturen in New Haven (nhtemp)") %>% 
  dyRangeSelector(dateWindow = c("1920-01-01", "1960-01-01"))
```

# Tabelle der größten Diamanten

```{r tabelle, results='markup'}
library(DT)
diamonds %>% 
  arrange(desc(carat)) %>% 
  head(50) %>% 
  select(carat, cut, color, price) %>% 
  datatable()
```

# OpenStreetMap Karten mit Leaflet

```{r leaflet}
library(leaflet)
leaflet() %>%
  setView(7.36, 49.262 , zoom = 15) %>% 
  addTiles() %>%
  addMarkers(7.3611, 49.262, popup = "Campus Zweibrücken") 
```

# Visualisierung von Graphen mit visNetwork


```{r tree, message=TRUE, warning=TRUE, , results='markup'}
nodes <- data.frame(id = 0:7,
                    level = c(1, 2, 2, 3, 3, 3, 3, 3),
                    label = LETTERS[1:8],
                    title = paste0(0:7),
                    shape = c("circle"),
                    size = 5,
                    title = paste0("<b>", 0:7,"</b>"),
                    color = c("lightblue"))

edges <- data.frame(from = c(0, 0, 1, 1, 1, 2, 2), 
                    to = c(1, 2, 3, 4, 5, 6, 7),
                    width = 4,
                    color = c("green"))

visNetwork(nodes, edges, 
           height = "80%", 
           width = "80%") %>%
    visEdges(arrows = "to") %>%
    visNodes(shadow=TRUE) %>%
    visInteraction(dragNodes = TRUE, 
                   dragView = TRUE, 
                   zoomView = TRUE,
                   keyboard = TRUE,
                   navigationButtons = TRUE) %>%
  visHierarchicalLayout(levelSeparation = 250)
```