---
title: "Wahrscheinlichkeitstheorie"
author: "Manfred Brill"
date: "Sommersemester 2021"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
    fig_caption: yes
    highligh: pygments
    theme: cosmo
    number_sections: yes
  html_notebook:
    highlight: pygments
    number_sections: yes
    theme: cosmo
    toc: yes
bibliography: literatur.bib
---

```{r setup, include=TRUE, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Rmd bearbeiten
library(knitr)
library(kableExtra)
# ggplot, Pipelines und mehr in Tidyverse
suppressPackageStartupMessages(library(dplyr))
library(tidyverse)

library(RColorBrewer)
myPalette <- brewer.pal(5, "YlGn")
# Ausgabe von double-Werte mit  zwei Stellen hinter dem Komma
options(digits=3)
```

# Voraussetzungen
Dieses Dokument setzt voraus, dass Sie bereits eine Lehrveranstaltung im Bereich Wahrscheinlichkeitsrechnung gehört haben. Ebenfalls wird vorausgesetzt,
 dass die grundlegenden Konzepte von R bekannt sind. Wo immer möglich wird das
Package *tidyverse* eingesetzt.


# Wahrscheinlichkeiten
Die Wahrscheinlichkeitstheorie, die mathematische Beschreibung von zufälligen Ereignissen, ist relativ jung. Man hat lange versucht die mathematischen Gesetze einer Wahrscheinlichkeit mathematisch zu fixieren. Dabei wurde lange versucht den Begriff einer Wahrscheinlichkeit mit Hilfe von Grenzübergängen aus den relativen Häufigkeiten abzuleiten, scheiterte aber immer wieder an Inkonsistenzen.
Kolmogorov hat letztendlich in den zwanziger Jahres des letzten Jahrhunderts Axiome formuliert, die die Basis dessen bilden was wir heute Wahrscheinlichkeitstheorie nennen. Interessant ist, dass in seiner Veröffentlichung der Begriff *Wahrscheinlichkeit* überhaupt nicht auftauchte.




# Literaturverzeichnis


