---
title: "Die erste HTML Präsentation mit IOSlides"
author: "Manfred Brill"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2, warn.conflicts = FALSE, quietly=TRUE)
library(dplyr, warn.conflicts = FALSE, quietly=TRUE)

diamonds.cut <- 2.5
smaller <- diamonds %>%
  filter(carat <= diamonds.cut)
```

## R Markdown

Dies ist eine [R Markdown](http://rmarkdown.rstudio.com) Präsentation. Als Option verwenden wir hier *ioslides*. Neue Folien erstellen wir
mit einer Überschrift der Stufe 2, also mit 
´## Überschrift´.

## Eine Folie mit Bullet Points

- Bullet 1
- Bullet 2
- Bullet 3

## Eine Folie mit R Ausgaben

```{r smaller, echo = TRUE}
smaller
```

## Eine Folie mit einer Grafik

```{r histogramm}
  ggplot(smaller, aes(carat)) +
  geom_histogram(binwidth = 0.05, fill="green", color="black") +
  labs(
    title="Datensatz diamonds - Verteilung der Karatzahlen unterhalb 2,5 Karat",
    x = "Karat",
    y = "Absolute Häufigkeit"
  )
```

